### ISSUE TITLE
mint 18 64bit fails

### ISSUE THREAD

**Issue by bash64** [Douane/douane-dkms#18]
```
$ sudo service douane start

 * Starting the douaned daemon
modprobe: FATAL: Module douane not found in directory /lib/modules/4.4.0-24-generic
```

I followed all of the latest dependency and compile instructions to the tee.

Are you compatible with kernel 4.4?

**Comment by bash64** [comment]
p.s. I notice you use systemD.
I boot using Upstart. 
systemD should still function though. I did not uninstall systemD.

**Comment by zedtux** [comment]
@bash64 please have a look at the PR Douane/douane-dkms#15 and [here](https://github.com/Douane/douane-dkms/issues/17#issuecomment-222370707) are the instructions in case you don't know how to deal with it.

**Comment by bash64** [comment]
sudo make dkms
Installing Douane Linux kernel module version 0.8.2...

Creating symlink /var/lib/dkms/douane/0.8.2/source ->
                 /usr/src/douane-0.8.2

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make KERNELRELEASE=4.4.0-24-generic -C /lib/modules/4.4.0-24-generic/build M=/var/lib/dkms/douane/0.8.2/build....(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.4.0-24-generic (x86_64)
Consult /var/lib/dkms/douane/0.8.2/build/make.log for more information.
Makefile:77: recipe for target 'dkms' failed
make: *** [dkms] Error 10

**Comment by bash64** [comment]
I did do rebuilddkms first and it failed. I then went into the original dkms folder and did make cleandkms. then came back and tried sudo make dkms on the new branch and got the above error.

**Comment by bash64** [comment]
I wouldn't mind trying a lower kernel, however, mint 18 comes with a minimum of 4.4.0-21.

**Comment by smarek** [comment]
@bash64 could you please provide the make log file? (mentioned in error message as in `/var/lib/dkms/douane/0.8.2/build/make.log` )

**Comment by bash64** [comment]
$ cat /var/lib/dkms/douane/0.8.2/build/make.log
DKMS make.log for douane-0.8.2 for kernel 4.4.0-24-generic (x86_64)
Mon Jul 11 12:33:33 EDT 2016
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-24-generic'
  LD      /var/lib/dkms/douane/0.8.2/build/built-in.o
  CC [M]  /var/lib/dkms/douane/0.8.2/build/douane.o
/var/lib/dkms/douane/0.8.2/build/douane.c:1115:15: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
   .hook     = netfiler_packet_hook,
               ^
/var/lib/dkms/douane/0.8.2/build/douane.c:1115:15: note: (near initialization for ‘nfho_outgoing.hook’)
/var/lib/dkms/douane/0.8.2/build/douane.c:1119:3: error: unknown field ‘owner’ specified in initializer
   .owner    = THIS_MODULE
   ^
In file included from include/linux/linkage.h:6:0,
                 from include/linux/kernel.h:6,
                 from include/linux/list.h:8,
                 from include/linux/module.h:9,
                 from /var/lib/dkms/douane/0.8.2/build/douane.c:17:
include/linux/export.h:34:21: warning: excess elements in struct initializer
 #define THIS_MODULE (&__this_module)
                     ^
/var/lib/dkms/douane/0.8.2/build/douane.c:1119:15: note: in expansion of macro ‘THIS_MODULE’
   .owner    = THIS_MODULE
               ^
include/linux/export.h:34:21: note: (near initialization for ‘nfho_outgoing’)
 #define THIS_MODULE (&__this_module)
                     ^
/var/lib/dkms/douane/0.8.2/build/douane.c:1119:15: note: in expansion of macro ‘THIS_MODULE’
   .owner    = THIS_MODULE
               ^
scripts/Makefile.build:264: recipe for target '/var/lib/dkms/douane/0.8.2/build/douane.o' failed
make[2]: *** [/var/lib/dkms/douane/0.8.2/build/douane.o] Error 1
Makefile:1402: recipe for target '_module_/var/lib/dkms/douane/0.8.2/build' failed
make[1]: *** [_module_/var/lib/dkms/douane/0.8.2/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-24-generic'

**Comment by smarek** [comment]
Yes, this is same problem, I've fixed with PR #15 (field .owner unknown, etc..)
Use patch from my PR, because you're obviously not using it .)

**Comment by bash64** [comment]
Ok, I don't see the instructions for using the PR.

**Comment by zedtux** [comment]
@bash64 the instructions are the same as described [here](https://github.com/Douane/douane-dkms/issues/17#issuecomment-222370707)

**Comment by bash64** [comment]
>git clone https://github.com/smarek/douane-dkms douane-dkms-smarek
>cd douane-dkms-smarek
>git checkout fix-kernel-freeze
>sudo make dkms

Installing Douane Linux kernel module version 0.8.2...

Creating symlink /var/lib/dkms/douane/0.8.2/source ->
                 /usr/src/douane-0.8.2

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make KERNELRELEASE=4.4.0-24-generic -C /lib/modules/4.4.0-24-generic/build M=/var/lib/dkms/douane/0.8.2/build.....(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.4.0-24-generic (x86_64)
Consult /var/lib/dkms/douane/0.8.2/build/make.log for more information.
Makefile:77: recipe for target 'dkms' failed
make: *** [dkms] Error 10


>cat /var/lib/dkms/douane/0.8.2/build/make.log
DKMS make.log for douane-0.8.2 for kernel 4.4.0-24-generic (x86_64)
Mon Jul 18 06:44:39 EDT 2016
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-24-generic'
  LD      /var/lib/dkms/douane/0.8.2/build/built-in.o
  CC [M]  /var/lib/dkms/douane/0.8.2/build/douane.o
/var/lib/dkms/douane/0.8.2/build/douane.c:1115:15: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
   .hook     = netfiler_packet_hook,
               ^
/var/lib/dkms/douane/0.8.2/build/douane.c:1115:15: note: (near initialization for ‘nfho_outgoing.hook’)
/var/lib/dkms/douane/0.8.2/build/douane.c:1119:3: error: unknown field ‘owner’ specified in initializer
   .owner    = THIS_MODULE
   ^
In file included from include/linux/linkage.h:6:0,
                 from include/linux/kernel.h:6,
                 from include/linux/list.h:8,
                 from include/linux/module.h:9,
                 from /var/lib/dkms/douane/0.8.2/build/douane.c:17:
include/linux/export.h:34:21: warning: excess elements in struct initializer
 #define THIS_MODULE (&__this_module)
                     ^
/var/lib/dkms/douane/0.8.2/build/douane.c:1119:15: note: in expansion of macro ‘THIS_MODULE’
   .owner    = THIS_MODULE
               ^
include/linux/export.h:34:21: note: (near initialization for ‘nfho_outgoing’)
 #define THIS_MODULE (&__this_module)
                     ^
/var/lib/dkms/douane/0.8.2/build/douane.c:1119:15: note: in expansion of macro ‘THIS_MODULE’
   .owner    = THIS_MODULE
               ^
scripts/Makefile.build:264: recipe for target '/var/lib/dkms/douane/0.8.2/build/douane.o' failed
make[2]: *** [/var/lib/dkms/douane/0.8.2/build/douane.o] Error 1
Makefile:1402: recipe for target '_module_/var/lib/dkms/douane/0.8.2/build' failed
make[1]: *** [_module_/var/lib/dkms/douane/0.8.2/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-24-generic'

**Comment by smarek** [comment]
skip this step, and you're fine "git checkout fix-kernel-freeze"

**Comment by bash64** [comment]
ok, compiled.

**Comment by bash64** [comment]
Douane-dialog:
>cd ~/Douane
>git clone --recursive https://github.com/Douane/douane-dialog
>cd douane-dialog
>make

massive errors compiling this.
Are the compile instructions correct from here: https://github.com/Douane/Douane/wiki/Compilation

**Comment by smarek** [comment]
again, they should be, provide the build log

**Comment by bash64** [comment]
ok, I deleted everything and started over.
dkms compiles just fine from smarek,
the daemon compiles with warnings, errors, and notes.
I start the daemon.

I cannot download dialog until i stop doaune-dameon.
it is blocking access to github.com so i stop the daemon.

i get warnings, errors, and notes and it fails.

that is where i am.
I have no issues following instructions here.
I have never seen the code in such bad shape before.
as I stated, I started over from scratch.

so where is the douane-dialog build log? is it the same build log for all of them?

**Comment by bash64** [comment]
Here are my dependencies:  
>sudo apt install build-essential libboost-filesystem-dev libboost-regex-dev libboost-signals-dev policykit-1 libdbus-c++-dev libdbus-1-dev liblog4cxx10-dev libssl-dev libgtkmm-3.0-dev gtk+3.0 python3 python3-gi policykit-1 python3-dbus

**Comment by bash64** [comment]
hold on, some of the dependencies were not installed.

**Comment by bash64** [comment]
get back with ya later on today

**Comment by zedtux** [comment]
> I cannot download dialog until i stop doaune-dameon.

@bash64 this is normal. As soon as you start Douane, all connection are blocked excepted the allowed one, but here you're starting from a blank list so all is blocked and the dialog is not install so can't popup.

> so where is the douane-dialog build log? is it the same build log for all of them?

All is logged in `/var/log/douane.log`.

> hold on, some of the dependencies were not installed.
> get back with ya later on today

OK so keep clam and restart from the beginning :)

**Comment by zedtux** [comment]
I close this issue as I have merge @Guimli's PR which fixes this issue.
