### ISSUE TITLE
Compilation Error Linux Mint 18.3 [Kernel 4.13.0.32-generic]

### ISSUE THREAD

**Issue by ripping-constable** [Douane/douane-dkms#29]
Hi, am trying to compile Douane and have installed the dependencies as detailed in the wiki.

When compiling douane-dkms I get the following error:

> sudo make dkms
> Installing Douane Linux kernel module version 0.8.2...
> 
> Creating symlink /var/lib/dkms/douane/0.8.2/source ->
>                  /usr/src/douane-0.8.2
> 
> DKMS: add completed.
> 
> Kernel preparation unnecessary for this kernel.  Skipping...
> 
> Building module:
> cleaning build area.....
> make KERNELRELEASE=4.13.0-32-generic -C /lib/modules/4.13.0-32-generic/build M=/var/lib/dkms/douane/0.8.2/build.........(bad exit status: 2)
> Error! Bad return status for module build on kernel: 4.13.0-32-generic (i686)
> Consult /var/lib/dkms/douane/0.8.2/build/make.log for more information.
> Makefile:77: recipe for target 'dkms' failed
> make: *** [dkms] Error 10

make.log output as follows:

> DKMS make.log for douane-0.8.2 for kernel 4.13.0-32-generic (i686)
> Sat Feb 17 01:49:51 +01 2018
> make[1]: Entering directory '/usr/src/linux-headers-4.13.0-32-generic'
>   AR      /var/lib/dkms/douane/0.8.2/build/built-in.o
>   CC [M]  /var/lib/dkms/douane/0.8.2/build/douane.o
> /var/lib/dkms/douane/0.8.2/build/douane.c: In function ‘task_exe_path’:
> /var/lib/dkms/douane/0.8.2/build/douane.c:713:5: error: implicit declaration of function ‘task_lock’ [-Werror=implicit-function-declaration]
>      task_lock(locked_task);
>      ^
> /var/lib/dkms/douane/0.8.2/build/douane.c:734:11: error: implicit declaration of function ‘task_unlock’ [-Werror=implicit-function-declaration]
>            task_unlock(locked_task);
>            ^
> /var/lib/dkms/douane/0.8.2/build/douane.c:759:5: error: expected ‘while’ before ‘while_each_thread’
>    } while_each_thread(task, locked_task);
>      ^
> /var/lib/dkms/douane/0.8.2/build/douane.c: In function ‘find_task_from_socket_file’:
> /var/lib/dkms/douane/0.8.2/build/douane.c:773:3: error: implicit declaration of function ‘for_each_process’ [-Werror=implicit-function-declaration]
>    for_each_process(task)
>    ^
> /var/lib/dkms/douane/0.8.2/build/douane.c:774:3: error: expected ‘;’ before ‘{’ token
>    {
>    ^
> /var/lib/dkms/douane/0.8.2/build/douane.c: In function ‘initialize_module’:
> /var/lib/dkms/douane/0.8.2/build/douane.c:1196:3: error: implicit declaration of function ‘nf_register_hook’ [-Werror=implicit-function-declaration]
>    nf_register_hook(&nfho_outgoing);
>    ^
> /var/lib/dkms/douane/0.8.2/build/douane.c: In function ‘exit_module’:
> /var/lib/dkms/douane/0.8.2/build/douane.c:1224:3: error: implicit declaration of function ‘nf_unregister_hook’ [-Werror=implicit-function-declaration]
>    nf_unregister_hook(&nfho_outgoing);
>    ^
> cc1: some warnings being treated as errors
> scripts/Makefile.build:315: recipe for target '/var/lib/dkms/douane/0.8.2/build/douane.o' failed
> make[2]: *** [/var/lib/dkms/douane/0.8.2/build/douane.o] Error 1
> Makefile:1550: recipe for target '_module_/var/lib/dkms/douane/0.8.2/build' failed
> make[1]: *** [_module_/var/lib/dkms/douane/0.8.2/build] Error 2
> make[1]: Leaving directory '/usr/src/linux-headers-4.13.0-32-generic'

 
Any help would be excellent - I really want to compile this!

**Comment by zedtux** [comment]
Duplicates #26. Please join us on #26
