### ISSUE TITLE
Compilation error on Kali Linux

### ISSUE THREAD

**Issue by Mato-Z** [Douane/douane-dkms#28]
Hello, during compilation douane-dkms on Kali Linux Rolling - SMP Debian 4.14.2-1kali1 (2017-12-04) x86_64 GNU/Linux I get this error:

```
/opt/Douane/douane-dkms# make dkms
Installing Douane Linux kernel module version 0.8.2...

Creating symlink /var/lib/dkms/douane/0.8.2/source ->
                 /usr/src/douane-0.8.2

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=4.14.0-kali1-amd64 -C /lib/modules/4.14.0-kali1-amd64/build M=/var/lib/dkms/douane/0.8.2/build...(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.14.0-kali1-amd64 (x86_64)
Consult /var/lib/dkms/douane/0.8.2/build/make.log for more information.
Makefile:77: recipe for target 'dkms' failed
make: *** [dkms] Error 10
```
make.log:
```
KMS make.log for douane-0.8.2 for kernel 4.14.0-kali1-amd64 (x86_64)
Ut jan  2 20:38:22 CET 2018
make[1]: Entering directory '/usr/src/linux-headers-4.14.0-kali1-amd64'
  AR      /var/lib/dkms/douane/0.8.2/build/built-in.o
  CC [M]  /var/lib/dkms/douane/0.8.2/build/douane.o
/var/lib/dkms/douane/0.8.2/build/douane.c: In function ‘task_exe_path’:
/var/lib/dkms/douane/0.8.2/build/douane.c:713:5: error: implicit declaration of function ‘task_lock’; did you mean ‘task_nice’? [-Werror=implicit-function-declaration]
     task_lock(locked_task);
     ^~~~~~~~~
     task_nice
/var/lib/dkms/douane/0.8.2/build/douane.c:734:11: error: implicit declaration of function ‘task_unlock’; did you mean ‘osq_unlock’? [-Werror=implicit-function-declaration]
           task_unlock(locked_task);
           ^~~~~~~~~~~
           osq_unlock
/var/lib/dkms/douane/0.8.2/build/douane.c:759:5: error: expected ‘while’ before ‘while_each_thread’
   } while_each_thread(task, locked_task);
     ^~~~~~~~~~~~~~~~~
/var/lib/dkms/douane/0.8.2/build/douane.c: In function ‘find_task_from_socket_file’:
/var/lib/dkms/douane/0.8.2/build/douane.c:773:3: error: implicit declaration of function ‘for_each_process’; did you mean ‘for_each_node’? [-Werror=implicit-function-declaration]
   for_each_process(task)
   ^~~~~~~~~~~~~~~~
   for_each_node
/var/lib/dkms/douane/0.8.2/build/douane.c:774:3: error: expected ‘;’ before ‘{’ token
   {
   ^
/var/lib/dkms/douane/0.8.2/build/douane.c: In function ‘initialize_module’:
/var/lib/dkms/douane/0.8.2/build/douane.c:1196:3: error: implicit declaration of function ‘nf_register_hook’; did you mean ‘nf_register_net_hook’? [-Werror=implicit-function-declaration]
   nf_register_hook(&nfho_outgoing);
   ^~~~~~~~~~~~~~~~
   nf_register_net_hook
/var/lib/dkms/douane/0.8.2/build/douane.c: In function ‘exit_module’:
/var/lib/dkms/douane/0.8.2/build/douane.c:1224:3: error: implicit declaration of function ‘nf_unregister_hook’; did you mean ‘nf_unregister_net_hook’? [-Werror=implicit-function-declaration]
   nf_unregister_hook(&nfho_outgoing);
   ^~~~~~~~~~~~~~~~~~
   nf_unregister_net_hook
cc1: some warnings being treated as errors
/usr/src/linux-headers-4.14.0-kali1-common/scripts/Makefile.build:325: recipe for target '/var/lib/dkms/douane/0.8.2/build/douane.o' failed
make[4]: *** [/var/lib/dkms/douane/0.8.2/build/douane.o] Error 1
/usr/src/linux-headers-4.14.0-kali1-common/Makefile:1520: recipe for target '_module_/var/lib/dkms/douane/0.8.2/build' failed
make[3]: *** [_module_/var/lib/dkms/douane/0.8.2/build] Error 2
Makefile:146: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.14.0-kali1-amd64'
```
Can you help me please?

**Comment by zedtux** [comment]
@Mato-Z your issue duplicates #26 so I'm closing it, please join issue #26
