### PR TITLE
Netfilter hooks changed to work with kernel version >= 4.13

### LINKED ISSUE #26: Build error on kernel 4.13.x
Hi, i got a compile error when building the module please help. I really like this project and would love to get it working!

My dependencies:
```
sudo dnf install dkms @development-tools "kernel-devel-uname-r == $(uname -r)"
```

Make:
```
# make dkms                                                                                                        
Installing Douane Linux kernel module version 0.8.2...                

Creating symlink /var/lib/dkms/douane/0.8.2/source ->                 
                 /usr/src/douane-0.8.2                                

DKMS: add completed.               

Kernel preparation unnecessary for this kernel.  Skipping...          

Building module:                   
cleaning build area...             
make -j4 KERNELRELEASE=4.13.12-300.fc27.x86_64 -C /lib/modules/4.13.12-300.fc27.x86_64/build M=/var/lib/dkms/douane/0.8.2/build...(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.13.12-300.fc27.x86_64 (x86_64)                                                       
Consult /var/lib/dkms/douane/0.8.2/build/make.log for more information.                                                                     
make: *** [Makefile:86: dkms] Error 10
```

Logfile:
```
# cat /var/lib/dkms/douane/0.8.2/build/make.log
DKMS make.log for douane-0.8.2 for kernel 4.13.12-300.fc27.x86_64 (x86_64)
Sun Nov 19 11:08:59 CET 2017
make[1]: Entering directory '/usr/src/kernels/4.13.12-300.fc27.x86_64'
  AR      /var/lib/dkms/douane/0.8.2/build/built-in.o
  CC [M]  /var/lib/dkms/douane/0.8.2/build/douane.o
/var/lib/dkms/douane/0.8.2/build/douane.c: In function ‘task_exe_path’:
/var/lib/dkms/douane/0.8.2/build/douane.c:713:5: error: implicit declaration of function ‘task_lock’; did you mean ‘txd_lock’? [-Werror=implicit-function-declaration]
     task_lock(locked_task);
     ^~~~~~~~~
     txd_lock
/var/lib/dkms/douane/0.8.2/build/douane.c:734:11: error: implicit declaration of function ‘task_unlock’; did you mean ‘tasklet_unlock’? [-Werror=implicit-function-declaration]
           task_unlock(locked_task);
           ^~~~~~~~~~~
           tasklet_unlock
/var/lib/dkms/douane/0.8.2/build/douane.c:759:5: error: expected ‘while’ before ‘while_each_thread’
   } while_each_thread(task, locked_task);
     ^~~~~~~~~~~~~~~~~
/var/lib/dkms/douane/0.8.2/build/douane.c: In function ‘find_task_from_socket_file’:
/var/lib/dkms/douane/0.8.2/build/douane.c:773:3: error: implicit declaration of function ‘for_each_process’; did you mean ‘for_each_node’? [-Werror=implicit-function-declaration]
   for_each_process(task)
   ^~~~~~~~~~~~~~~~
   for_each_node
/var/lib/dkms/douane/0.8.2/build/douane.c:774:3: error: expected ‘;’ before ‘{’ token
   {
   ^
/var/lib/dkms/douane/0.8.2/build/douane.c: In function ‘initialize_module’:
/var/lib/dkms/douane/0.8.2/build/douane.c:1196:3: error: implicit declaration of function ‘nf_register_hook’; did you mean ‘nf_register_net_hook’? [-Werror=implicit-function-declaration]
   nf_register_hook(&nfho_outgoing);
   ^~~~~~~~~~~~~~~~
   nf_register_net_hook
/var/lib/dkms/douane/0.8.2/build/douane.c: In function ‘exit_module’:
/var/lib/dkms/douane/0.8.2/build/douane.c:1224:3: error: implicit declaration of function ‘nf_unregister_hook’; did you mean ‘nf_unregister_net_hook’? [-Werror=implicit-function-declaration]
   nf_unregister_hook(&nfho_outgoing);
   ^~~~~~~~~~~~~~~~~~
   nf_unregister_net_hook
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:309: /var/lib/dkms/douane/0.8.2/build/douane.o] Error 1
make[1]: *** [Makefile:1516: _module_/var/lib/dkms/douane/0.8.2/build] Error 2
make[1]: Leaving directory '/usr/src/kernels/4.13.12-300.fc27.x86_64'
```

any help appreciated :)

### PR DESCRIPTION
**Pull request by cynay**
Fixes #26

### CODE REVIEW

File: douane.c [hunk 1]
```diff
@@ -1221,7 +1226,7 @@ static void __exit exit_module(void)
     activities_socket = NULL;
   }
 
-  nf_unregister_hook(&nfho_outgoing);
+  nf_unregister_net_hook(&init_net, &nfho_outgoing);
```
Comment (zedtux) [inline douane.c]: The compilation condition you did for the `nf_register_net_hook` is required here too. Please add it.

File: douane.c [hunk 2]
```diff
@@ -1193,7 +1194,11 @@ static int __init initialize_module(void)
   INIT_LIST_HEAD(&process_socket_inodes.list);
 
   // Hook to Netfilter
+#if LINUX_VERSION_CODE <= KERNEL_VERSION(4,12,14)
   nf_register_hook(&nfho_outgoing);
+#else
+  nf_register_net_hook(&init_net, &nfho_outgoing);
```
Comment (zedtux) [inline douane.c]: So there are no changes to [the `static struct nf_hook_ops nfho_outgoing`](https://github.com/cynay/douane-dkms/blob/34c7f35059ba80026eae88226689aa4397027036/douane.c#L1174) used to initialise the hook?

**Review by zedtux — CHANGES_REQUESTED** [review]

File: douane.c (hunk 1 above)
Comment (cynay) [reply douane.c]: Yes of course ... it was late already when i implemented this 😄

**Comment by zedtux** [comment]
@cynay can you please merge master in your branch so that you can fix the conflict following the merge of #30?

**Comment by cynay** [comment]
@zedtux I have merged your master into mine.

File: douane.c (hunk 2 above)
Comment (cynay) [reply douane.c]: nf_hook_ops is the same as before (adding the .dev caused a freeze and is not needet because we filter on every device)

**Comment by cynay** [comment]
@zedtux should be good to merge into your master if you want.

**Review by zedtux — APPROVED** [review]

File: douane.c [hunk 3]
```diff
@@ -1182,6 +1181,9 @@ static struct nf_hook_ops nfho_outgoing = {
   .hooknum  = NF_IP_LOCAL_OUT,
   .pf       = NFPROTO_IPV4,
   .priority = NF_IP_PRI_LAST,
+#if LINUX_VERSION_CODE <= KERNEL_VERSION(4,12,14)
+//  .dev	    = , // .dev is not used!
```
Comment (zedtux) [inline douane.c]: This looks strange to me. If the `.dev` is never used (meaning across all Linux kernel versions) then remove the entire `if` otherwise uncomment it.

File: douane.c [hunk 4]
```diff
@@ -1195,12 +1197,25 @@ static int __init initialize_module(void)
 {
 #ifdef DEBUG
   printk(KERN_INFO "douane:%d:%s: Initializing module\n", __LINE__, __FUNCTION__);
+
+  // Net Device debugging
+  struct net_device *dev = first_net_device(&init_net);
+  while(dev)
+  {
+    printk(KERN_INFO "douane:%d:%s: Net_Device found: name: %s - ifindex: %d\n", __LINE__, __FUNCTION__, dev->name, dev->ifindex);
```
Comment (zedtux) [inline douane.c]: I like it 👍

**Review by zedtux — CHANGES_REQUESTED** [review]
Just this `if` with the `.dev` commented to be updated and I'll merge this PR.

**Review by zedtux — APPROVED** [review]

**Comment by cynay** [comment]
I removed the unused .dev

**Comment by zedtux** [comment]
Thank you very much @cynay for your contribution 🏅 🎉
