### ISSUE TITLE
Build error on kernel 4.13.x

### ISSUE THREAD

**Issue by cynay** [Douane/douane-dkms#26]
Hi, i got a compile error when building the module please help. I really like this project and would love to get it working!

My dependencies:
```
sudo dnf install dkms @development-tools "kernel-devel-uname-r == $(uname -r)"
```

Make:
```
# make dkms                                                                                                        
Installing Douane Linux kernel module version 0.8.2...                

Creating symlink /var/lib/dkms/douane/0.8.2/source ->                 
                 /usr/src/douane-0.8.2                                

DKMS: add completed.               

Kernel preparation unnecessary for this kernel.  Skipping...          

Building module:                   
cleaning build area...             
make -j4 KERNELRELEASE=4.13.12-300.fc27.x86_64 -C /lib/modules/4.13.12-300.fc27.x86_64/build M=/var/lib/dkms/douane/0.8.2/build...(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.13.12-300.fc27.x86_64 (x86_64)                                                       
Consult /var/lib/dkms/douane/0.8.2/build/make.log for more information.                                                                     
make: *** [Makefile:86: dkms] Error 10
```

Logfile:
```
# cat /var/lib/dkms/douane/0.8.2/build/make.log
DKMS make.log for douane-0.8.2 for kernel 4.13.12-300.fc27.x86_64 (x86_64)
Sun Nov 19 11:08:59 CET 2017
make[1]: Entering directory '/usr/src/kernels/4.13.12-300.fc27.x86_64'
  AR      /var/lib/dkms/douane/0.8.2/build/built-in.o
  CC [M]  /var/lib/dkms/douane/0.8.2/build/douane.o
/var/lib/dkms/douane/0.8.2/build/douane.c: In function ‘task_exe_path’:
/var/lib/dkms/douane/0.8.2/build/douane.c:713:5: error: implicit declaration of function ‘task_lock’; did you mean ‘txd_lock’? [-Werror=implicit-function-declaration]
     task_lock(locked_task);
     ^~~~~~~~~
     txd_lock
/var/lib/dkms/douane/0.8.2/build/douane.c:734:11: error: implicit declaration of function ‘task_unlock’; did you mean ‘tasklet_unlock’? [-Werror=implicit-function-declaration]
           task_unlock(locked_task);
           ^~~~~~~~~~~
           tasklet_unlock
/var/lib/dkms/douane/0.8.2/build/douane.c:759:5: error: expected ‘while’ before ‘while_each_thread’
   } while_each_thread(task, locked_task);
     ^~~~~~~~~~~~~~~~~
/var/lib/dkms/douane/0.8.2/build/douane.c: In function ‘find_task_from_socket_file’:
/var/lib/dkms/douane/0.8.2/build/douane.c:773:3: error: implicit declaration of function ‘for_each_process’; did you mean ‘for_each_node’? [-Werror=implicit-function-declaration]
   for_each_process(task)
   ^~~~~~~~~~~~~~~~
   for_each_node
/var/lib/dkms/douane/0.8.2/build/douane.c:774:3: error: expected ‘;’ before ‘{’ token
   {
   ^
/var/lib/dkms/douane/0.8.2/build/douane.c: In function ‘initialize_module’:
/var/lib/dkms/douane/0.8.2/build/douane.c:1196:3: error: implicit declaration of function ‘nf_register_hook’; did you mean ‘nf_register_net_hook’? [-Werror=implicit-function-declaration]
   nf_register_hook(&nfho_outgoing);
   ^~~~~~~~~~~~~~~~
   nf_register_net_hook
/var/lib/dkms/douane/0.8.2/build/douane.c: In function ‘exit_module’:
/var/lib/dkms/douane/0.8.2/build/douane.c:1224:3: error: implicit declaration of function ‘nf_unregister_hook’; did you mean ‘nf_unregister_net_hook’? [-Werror=implicit-function-declaration]
   nf_unregister_hook(&nfho_outgoing);
   ^~~~~~~~~~~~~~~~~~
   nf_unregister_net_hook
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:309: /var/lib/dkms/douane/0.8.2/build/douane.o] Error 1
make[1]: *** [Makefile:1516: _module_/var/lib/dkms/douane/0.8.2/build] Error 2
make[1]: Leaving directory '/usr/src/kernels/4.13.12-300.fc27.x86_64'
```

any help appreciated :)

**Comment by zedtux** [comment]
Thank you @cynay for your issue.

As far as I can see, you're using Fedora and you're the very first one contacting me for this distribution. If I'm not mistaking you're using the Linux Kernel version 4.13.12 which seems to not be supported.

Based on your error message, I could say that the function `nf_register_hook` has been renamed to `nf_register_net_hook`, and same for `nf_unregister_hook`.

Can you please update the file `/var/lib/dkms/douane/0.8.2/build/douane.c` and change the method name and retry to build the kernel module?

If it's working, then PR are welcome :)

**Comment by cynay** [comment]
Hi @zedtux , thanks alot for your answer.

I tried to change the functions but without success. I have to say i'm not very fluent with C and i never did code modules or something like that. 

As far as i can tell the problem is now with the struct nf_hook_ops which needs additional parameters.
`struct nf_hook_ops {
	/* User fills in from here down. */
	nf_hookfn		*hook;
	struct net_device	*dev;
	void			*priv;
	u_int8_t		pf;
	unsigned int		hooknum;
	/* Hooks are ordered in ascending priority. */
	int			priority;
};`

`
DKMS make.log for douane-0.8.2 for kernel 4.13.12-300.fc27.x86_64 (x86_64)
Tue Nov 21 10:28:39 CET 2017
make[2]: Entering directory '/usr/src/kernels/4.13.12-300.fc27.x86_64'
  AR      /var/lib/dkms/douane/0.8.2/build/built-in.o
  CC [M]  /var/lib/dkms/douane/0.8.2/build/douane.o
/var/lib/dkms/douane/0.8.2/build/douane.c: In function ‘task_exe_path’:
/var/lib/dkms/douane/0.8.2/build/douane.c:713:5: error: implicit declaration of function ‘task_lock’; did you mean ‘txd_lock’? [-Werror=implicit-function-declaration]
     task_lock(locked_task);
     ^~~~~~~~~
     txd_lock
/var/lib/dkms/douane/0.8.2/build/douane.c:734:11: error: implicit declaration of function ‘task_unlock’; did you mean ‘tasklet_unlock’? [-Werror=implicit-function-declaration]
           task_unlock(locked_task);
           ^~~~~~~~~~~
           tasklet_unlock
/var/lib/dkms/douane/0.8.2/build/douane.c:759:5: error: expected ‘while’ before ‘while_each_thread’
   } while_each_thread(task, locked_task);
     ^~~~~~~~~~~~~~~~~
/var/lib/dkms/douane/0.8.2/build/douane.c: In function ‘find_task_from_socket_file’:
/var/lib/dkms/douane/0.8.2/build/douane.c:773:3: error: implicit declaration of function ‘for_each_process’; did you mean ‘for_each_node’? [-Werror=implicit-function-declaration]
   for_each_process(task)
   ^~~~~~~~~~~~~~~~
   for_each_node
/var/lib/dkms/douane/0.8.2/build/douane.c:774:3: error: expected ‘;’ before ‘{’ token
   {
   ^
/var/lib/dkms/douane/0.8.2/build/douane.c: In function ‘initialize_module’:
/var/lib/dkms/douane/0.8.2/build/douane.c:1196:24: error: passing argument 1 of ‘nf_register_net_hook’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   nf_register_net_hook(&nfho_outgoing);
                        ^
In file included from /var/lib/dkms/douane/0.8.2/build/douane.c:20:0:
./include/linux/netfilter.h:154:5: note: expected ‘struct net *’ but argument is of type ‘struct nf_hook_ops *’
 int nf_register_net_hook(struct net *net, const struct nf_hook_ops *ops);
     ^~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/douane/0.8.2/build/douane.c:1196:3: error: too few arguments to function ‘nf_register_net_hook’
   nf_register_net_hook(&nfho_outgoing);
   ^~~~~~~~~~~~~~~~~~~~
In file included from /var/lib/dkms/douane/0.8.2/build/douane.c:20:0:
./include/linux/netfilter.h:154:5: note: declared here
 int nf_register_net_hook(struct net *net, const struct nf_hook_ops *ops);
     ^~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/douane/0.8.2/build/douane.c: In function ‘exit_module’:
/var/lib/dkms/douane/0.8.2/build/douane.c:1224:26: error: passing argument 1 of ‘nf_unregister_net_hook’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   nf_unregister_net_hook(&nfho_outgoing);
In file included from /var/lib/dkms/douane/0.8.2/build/douane.c:20:0:
./include/linux/netfilter.h:155:6: note: expected ‘struct net *’ but argument is of type ‘struct nf_hook_ops *’
 void nf_unregister_net_hook(struct net *net, const struct nf_hook_ops *ops);
      ^~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/douane/0.8.2/build/douane.c:1224:3: error: too few arguments to function ‘nf_unregister_net_hook’
   nf_unregister_net_hook(&nfho_outgoing);
   ^~~~~~~~~~~~~~~~~~~~~~
In file included from /var/lib/dkms/douane/0.8.2/build/douane.c:20:0:
./include/linux/netfilter.h:155:6: note: declared here
 void nf_unregister_net_hook(struct net *net, const struct nf_hook_ops *ops);
      ^~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:309: /var/lib/dkms/douane/0.8.2/build/douane.o] Error 1
make[2]: *** [Makefile:1516: _module_/var/lib/dkms/douane/0.8.2/build] Error 2
make[2]: Leaving directory '/usr/src/kernels/4.13.12-300.fc27.x86_64'
`

If i get it working I sure will make a PR :)

**Comment by zedtux** [comment]
@cynay okay thank you for trying :)

Well as far as I can see, there is this `expected ‘struct net *’ but argument is of type ‘struct nf_hook_ops *’` so I think the `nf_hook_ops` struct should be replaced by the `net` one I guess ...

**Comment by cynay** [comment]
Hi again

Ok I'm progressing :) The modul is running
```
$ lsmod |grep douane
douane                 24576  0
```

I added an empty struct net for testing. I could solve the other errors (error: implicit declaration) by adding:
```
#include <linux/sched/signal.h>   // for_each_process(), task_lock(), task_unlock()
```
This is linked to this Issue:  #24 

Now i have problems with the daemon:
Logfile (cleaned):
```
21/11/2017 21:07:44 | daemon |  INFO | [main.cpp::Main:248]: The log file is /var/log/douane.log
21/11/2017 21:07:44 | daemon | DEBUG | [main.cpp::Main:251]: The debug mode is enabled
21/11/2017 21:07:44 | daemon | DEBUG | [main.cpp::Main:256]: Initializing DesktopFiles21/11/2017 21:07:44 | daemon | DEBUG | [freedesktop/desktop_file.cpp::DesktopFile:7]: Processing file "/usr/share/applications/FILE1.desktop" 
<CUT LINES>
21/11/2017 21:07:44 | daemon |  INFO | [freedesktop/desktop_files.cpp::DesktopFiles:7]: Loaded 216 Freedesktop desktop files
21/11/2017 21:11:41 | daemon | DEBUG | [main.cpp::Main:259]: Initializing RulesManager
21/11/2017 21:11:41 | daemon | DEBUG | [rules_manager.cpp::RulesManager:126]: RulesManager::load_rules_from_file...
21/11/2017 21:11:41 | daemon | DEBUG | [tools.cpp::Tools:49]: Douane root path is /opt/douane
21/11/2017 21:11:41 | daemon | ERROR | [rules_manager.cpp::RulesManager:135]: Unable to open the file /opt/douane/rules
21/11/2017 21:11:41 | daemon | DEBUG | [rules_manager.cpp::RulesManager:7]: RulesManager initialization done
21/11/2017 21:11:41 | daemon | DEBUG | [main.cpp::Main:262]: Initializing ProcessesManager
21/11/2017 21:11:41 | daemon | DEBUG | [main.cpp::Main:267]: Initializing DBusServer
21/11/2017 21:11:41 | daemon | DEBUG | [dbus/dbus_server.cpp::DBusServer:8]: Initializing D-Bus server
21/11/2017 21:11:41 | daemon | DEBUG | [main.cpp::Main:277]: Connecting objects
21/11/2017 21:11:41 | daemon | DEBUG | [main.cpp::Main:315]: Starting to listen to LKM. Daemon is alive!
21/11/2017 21:11:41 | daemon | DEBUG | [netlink_listener.cpp::NetlinkListener:163]: NetlinkListener::build_message...
21/11/2017 21:11:41 | daemon | DEBUG | [netlink_listener.cpp::NetlinkListener:155]: NetlinkListener is sending the hand check
21/11/2017 21:11:41 | daemon | DEBUG | [dbus/dbus_server.cpp::DBusServer:25]: Initializing D-Bus server...
21/11/2017 21:11:41 | daemon | DEBUG | [rules_manager.cpp::RulesManager:163]: RulesManager::push_rules...
21/11/2017 21:11:41 | daemon | DEBUG | [rules_manager.cpp::RulesManager:164]: 0 rules to be pushed.
21/11/2017 21:11:41 | daemon | DEBUG | [netlink_listener.cpp::NetlinkListener:28]: Payload size is 16472
21/11/2017 21:11:41 | daemon | DEBUG | [netlink_listener.cpp::NetlinkListener:30]: Entering LKM communication loop...
21/11/2017 21:11:41 | daemon | DEBUG | [dbus/douane.cpp::Douane:7]: Douane::Douane...
21/11/2017 21:11:41 | daemon | DEBUG | [dbus/douane.cpp::Douane:18]: Douane::set_rules_manager...
21/11/2017 21:11:41 | daemon | DEBUG | [dbus/douane.cpp::Douane:20]: Douane::set_rules_manager done
21/11/2017 21:11:41 | daemon | DEBUG | [dbus/dbus_server.cpp::DBusServer:34]: D-Bus server Initialized
21/11/2017 21:11:41 | daemon | DEBUG | [dbus/dbus_server.cpp::DBusServer:36]: Starting D-Bus server...
```

The dialog isn't working (when i start it it flashes for like 20ms in the Taskbar and prints out the following:
```
log4cxx: setFile(/var/log/douane.log,true) call failed.
log4cxx: IO Exception : status code = 13
log4cxx: setFile(/var/log/douane.log,true) call failed.
log4cxx: IO Exception : status code = 13
log4cxx: No output stream or file set for the appender named [].
```

The configurator has a module error:
```
Traceback (most recent call last):                                    
  File "./douane-configurator", line 2, in <module>                   
    from gi.repository import Gtk, GLib, Gdk                          
ImportError: No module named 'gi' 
```
I think i installed a wrong lib ...

if you have any input I'm very happy

**Comment by zedtux** [comment]
> I added an empty struct net for testing.

I think this will make Douane not hooking to the Linux Kernel Netfilter module, meaning no packet capture, so you will never see any dialog opening, but at least it confirms that with the version 4.13.x (we should figure out when the method has been renamed in order to write the right compilation condition).

Regarding your error `IO Exception : status code = 13` to me it sounds like permission issue on that file.

And for your last issue, maybe this is a solution: https://bugs.launchpad.net/gui-ufw/+bug/1566056/comments/1 (which would be weird as the Wiki should cover all dependencies installation ... but the Wiki is for Debian and Ubuntu).

**Comment by cynay** [comment]
Looks like the global hooks (nf_register_hook) where removed in Kernel 4.13.x (https://elixir.free-electrons.com/linux/v4.13/source/include/linux/netfilter.h) in 4.12.14 they are still present. 

I try to fix the Kernel module with a right net namespace and test again.

**Comment by cynay** [comment]
Hi @zedtux 
I create a Pull request with the fix for kernel version over 4.12.14. 
The App-Firewall is working now as expected :)
Thanks alot for your input.

**Comment by zedtux** [comment]
Great job @cynay! I will do the code review. Stay tune.

**Comment by Mato-Z** [comment]
@zedtux hello, thanks so I am continuing here. I applied modifications that you and @cynay  post above. But I have still problems my log: Many thanks fro help. 
```

DKMS make.log for douane-0.8.2 for kernel 4.14.0-kali1-amd64 (x86_64)
Ut jan  9 16:31:31 CET 2018
make[1]: Entering directory '/usr/src/linux-headers-4.14.0-kali1-amd64'
  AR      /var/lib/dkms/douane/0.8.2/build/built-in.o
  CC [M]  /var/lib/dkms/douane/0.8.2/build/douane.o
/var/lib/dkms/douane/0.8.2/build/douane.c:1174:15: error: variable ‘nfho_outgoing’ has initializer but incomplete type
 static struct nf_net_hook_ops nfho_outgoing = {
               ^~~~~~~~~~~~~~~
/var/lib/dkms/douane/0.8.2/build/douane.c:1175:4: error: ‘struct nf_net_hook_ops’ has no member named ‘hook’
   .hook     = netfiler_packet_hook,
    ^~~~
/var/lib/dkms/douane/0.8.2/build/douane.c:1175:15: warning: excess elements in struct initializer
   .hook     = netfiler_packet_hook,
               ^~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/douane/0.8.2/build/douane.c:1175:15: note: (near initialization for ‘nfho_outgoing’)
/var/lib/dkms/douane/0.8.2/build/douane.c:1176:4: error: ‘struct nf_net_hook_ops’ has no member named ‘hooknum’
   .hooknum  = NF_IP_LOCAL_OUT,
    ^~~~~~~
/var/lib/dkms/douane/0.8.2/build/douane.c:26:25: warning: excess elements in struct initializer
 #define NF_IP_LOCAL_OUT 3
                         ^
/var/lib/dkms/douane/0.8.2/build/douane.c:1176:15: note: in expansion of macro ‘NF_IP_LOCAL_OUT’
   .hooknum  = NF_IP_LOCAL_OUT,
               ^~~~~~~~~~~~~~~
/var/lib/dkms/douane/0.8.2/build/douane.c:26:25: note: (near initialization for ‘nfho_outgoing’)
 #define NF_IP_LOCAL_OUT 3
                         ^
/var/lib/dkms/douane/0.8.2/build/douane.c:1176:15: note: in expansion of macro ‘NF_IP_LOCAL_OUT’
   .hooknum  = NF_IP_LOCAL_OUT,
               ^~~~~~~~~~~~~~~
/var/lib/dkms/douane/0.8.2/build/douane.c:1177:4: error: ‘struct nf_net_hook_ops’ has no member named ‘pf’
   .pf       = NFPROTO_IPV4,
    ^~
/var/lib/dkms/douane/0.8.2/build/douane.c:1177:15: warning: excess elements in struct initializer
   .pf       = NFPROTO_IPV4,
               ^~~~~~~~~~~~
/var/lib/dkms/douane/0.8.2/build/douane.c:1177:15: note: (near initialization for ‘nfho_outgoing’)
/var/lib/dkms/douane/0.8.2/build/douane.c:1178:4: error: ‘struct nf_net_hook_ops’ has no member named ‘priority’
   .priority = NF_IP_PRI_LAST,
    ^~~~~~~~
/var/lib/dkms/douane/0.8.2/build/douane.c:1178:15: warning: excess elements in struct initializer
   .priority = NF_IP_PRI_LAST,
               ^~~~~~~~~~~~~~
/var/lib/dkms/douane/0.8.2/build/douane.c:1178:15: note: (near initialization for ‘nfho_outgoing’)
/var/lib/dkms/douane/0.8.2/build/douane.c: In function ‘initialize_module’:
/var/lib/dkms/douane/0.8.2/build/douane.c:1197:3: warning: statement with no effect [-Wunused-value]
   nf_register_net_hook//nf_register_hook(&nfho_outgoing);
   ^~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/douane/0.8.2/build/douane.c:1200:3: error: expected ‘;’ before ‘if’
   if (initialize_activities_socket() < 0)
   ^~
/var/lib/dkms/douane/0.8.2/build/douane.c: In function ‘exit_module’:
/var/lib/dkms/douane/0.8.2/build/douane.c:1225:26: error: passing argument 1 of ‘nf_unregister_net_hook’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   nf_unregister_net_hook(&nfho_outgoing);//nf_unregister_hook(&nfho_outgoing);
                          ^
In file included from /var/lib/dkms/douane/0.8.2/build/douane.c:20:0:
/usr/src/linux-headers-4.14.0-kali1-common/include/linux/netfilter.h:157:6: note: expected ‘struct net *’ but argument is of type ‘struct nf_net_hook_ops *’
 void nf_unregister_net_hook(struct net *net, const struct nf_hook_ops *ops);
      ^~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/douane/0.8.2/build/douane.c:1225:3: error: too few arguments to function ‘nf_unregister_net_hook’
   nf_unregister_net_hook(&nfho_outgoing);//nf_unregister_hook(&nfho_outgoing);
   ^~~~~~~~~~~~~~~~~~~~~~
In file included from /var/lib/dkms/douane/0.8.2/build/douane.c:20:0:
/usr/src/linux-headers-4.14.0-kali1-common/include/linux/netfilter.h:157:6: note: declared here
 void nf_unregister_net_hook(struct net *net, const struct nf_hook_ops *ops);
      ^~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/douane/0.8.2/build/douane.c: At top level:
/var/lib/dkms/douane/0.8.2/build/douane.c:1174:31: error: storage size of ‘nfho_outgoing’ isn’t known
 static struct nf_net_hook_ops nfho_outgoing = {
                               ^~~~~~~~~~~~~
cc1: some warnings being treated as errors
/usr/src/linux-headers-4.14.0-kali1-common/scripts/Makefile.build:325: recipe for target '/var/lib/dkms/douane/0.8.2/build/douane.o' failed
make[4]: *** [/var/lib/dkms/douane/0.8.2/build/douane.o] Error 1
/usr/src/linux-headers-4.14.0-kali1-common/Makefile:1520: recipe for target '_module_/var/lib/dkms/douane/0.8.2/build' failed
make[3]: *** [_module_/var/lib/dkms/douane/0.8.2/build] Error 2
Makefile:146: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
```

**Comment by cynay** [comment]
Hi @Mato-Z 
I think the Problem is with Kernel 4.14.x. I got everything working on my VM with Kernel 4.13.x but on my main system with Kernel 4.14.x I also got new problems.

Will have a look at it as soon as possible but this could take some time...

**Comment by Mato-Z** [comment]
Hi @cynay, ok, thanks a lot.

**Comment by Mato-Z** [comment]
Hi @cynay have you any progress please?

**Comment by cynay** [comment]
Hi @Mato-Z  sorry but i didn't find any time so far (Got a newborn at home and this eats my coding time :) )

**Comment by zedtux** [comment]
Congrats @cynay !! 🎉 Same for me 😉

**Comment by Mato-Z** [comment]
@cynay, @zedtux congrats too. @zedtux Do you have any idea for fix this bug?  Douane is great tool, if it stay in this state it will be a big pity... :-(

**Comment by zedtux** [comment]
@Mato-Z for now I'm bringing all the people having the same issue here hoping for someone to find a solution.

I don't know the fix but I know the reason: New Linux Kernel changes the Netfilter module and some code adaptation needs to be done here, [like it has already be done in the past](https://github.com/Douane/douane-dkms/blob/master/douane.c#L457).

Usually I was a website storing the Linux kernel versions with a search engine and comparing versions in order to figure out what has changed (Not sure anymore but I think it was [free electron](https://elixir.bootlin.com/linux/latest/source)).

An example I just found with google is [nf_register_hook not found in linux kernel 4.13-rc2 and later](https://unix.stackexchange.com/questions/413797/nf-register-hook-not-found-in-linux-kernel-4-13-rc2-and-later).

**Comment by cynay** [comment]
Also Congrats @zedtux  😄 
I've got it working but after a short time everything freezes and i don't really know how i can debug this.
You can see my changes here: https://github.com/cynay/douane-dkms/blob/master/douane.c

Changes:
Lines: 1174ff
```
static struct nf_hook_ops nfho_outgoing = {
  .hook     = netfiler_packet_hook,
  .hooknum  = NF_IP_LOCAL_OUT,
  .pf       = NFPROTO_IPV4,
  .priority = NF_IP_PRI_LAST,
#if LINUX_VERSION_CODE <= KERNEL_VERSION(4,12,14)
  .dev	    = dev_get_by_name(&init_net, "enp0s25"),
# endif
#if LINUX_VERSION_CODE < KERNEL_VERSION(4,4,0)
  .owner    = THIS_MODULE
#endif
};
```
Lines: 1191ff
```
static int __init initialize_module(void)
{
#ifdef DEBUG
  printk(KERN_INFO "douane:%d:%s: Initializing module\n", __LINE__, __FUNCTION__);

  // Net Device debugging
  struct net_device *dev = first_net_device(&init_net);
  while(dev)
  {
    printk(KERN_INFO "douane:%d:%s: Net_Device found: name: %s - ifindex: %d\n", __LINE__, __FUNCTION__, dev->name, dev->ifindex);
    dev = next_net_device(dev);
  }
#endif
  INIT_LIST_HEAD(&rules.list);
  INIT_LIST_HEAD(&process_socket_inodes.list);
  
 
  // Hook to Netfilter
#if LINUX_VERSION_CODE <= KERNEL_VERSION(4,12,14)
  nf_register_hook(&nfho_outgoing);
#else
  nf_register_net_hook(&init_net, &nfho_outgoing);
#endif
```

I've addes some debugging to list the net_devices: 
![selection_010](https://user-images.githubusercontent.com/275718/36729611-155f4a44-1bc5-11e8-86bb-196bbcb71ac2.png)

Like I said i freeze my whole VM after a short time with the only option to reset my VM (2 cores): 
![selection_009](https://user-images.githubusercontent.com/275718/36729690-51f9feb8-1bc5-11e8-9e8a-727fe1b6b86d.png)

I have the net_device hardcoded for testing purpose which has to be changed of course. It should filter on all active interfaces.

Any input is much appreciated 😃

**Comment by zedtux** [comment]
Thanks @cynay. 😃.

Well that's a good start and yeah, debugging in the kernel is something hard for me too. At the moment I was writing Douane, I had a working way which is no more working.
I have [described my solution](http://blog.zedroot.org/linux-kernel-debuging-using-kdump-and-crash/) at that time on [my blog](http://blog.zedroot.org/).

So if you find a working way, I would appreciate a lot you share it 👍

**Comment by zedtux** [comment]
@Mato-Z a fix by @cynay has been merged in the `master` branch, can you please refresh and retry?

**Comment by Mato-Z** [comment]
@cynay @zedtux I am very sorry for my late reply. Many thanks! Compilation was done successfully. But unfortunately I have a big problem with stability of my system please see https://github.com/Douane/douane-dkms/issues/31

**Comment by zedtux** [comment]
@Mato-Z the issue you reported about stability and this issue are 2 different things. This issue should stay closed as it has been fixed. Instead you should contribute to the issue #3.
